# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
# Primary
    lane :primary_ci do
        gradle(
          task: "test",
          build_type: "debug"
        )

        build_android_app(
          task: "assemble",
          build_type: "debug"
        )
    end

# Deploy Internal - Nightly
    lane :build_internal do
        primary_ci()

        configure_testlab_internal()
    end

    lane :deploy_internal do
        ensure_env_vars(
          env_vars: ['FIREBASE_APP_ID', 'BITRISE_DEBUG_APK', 'FIREBASE_TOKEN']
        )

        firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            release_notes: "Happy testing!",
            groups: "internal",
            apk_path: ENV['BITRISE_DEBUG_APK']
        )
    end

    # Add BITRISE_TEST_LAB_APK to the step in Bitrise as app path
    private_lane :configure_testlab_internal do
        sh("bash /bitrise/src/scripts/configure_firebase_testlab.sh")
        sh("envman add --key BITRISE_TEST_LAB_APK --value $BITRISE_DEBUG_APK")
    end

# Deploy Client - Manual
    lane :build_client do
        gradle(
          task: "test",
          build_type: "release"
        )

        sh("bash /bitrise/src/scripts/scrape_release_notes.sh")

        android_set_version_name(
          version_name: File.read(ENV['VERSION_NAME_PATH'])
        )

        build_android_app(
          task: "assemble",
          build_type: "release"
        )

        configure_testlab_release()
    end

    lane :deploy_client do
        ensure_env_vars(
            env_vars: ['FIREBASE_APP_ID', 'BITRISE_RELEASE_APK', 'FIREBASE_TOKEN', 'RELEASE_NOTES_PATH']
        )

        firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            release_notes_file: ENV['RELEASE_NOTES_PATH'],
            groups: "client",
            apk_path: ENV['BITRISE_RELEASE_APK']
        )

        clean_up()
    end

    private_lane :configure_testlab_release do
        sh("bash /bitrise/src/scripts/configure_firebase_testlab.sh")
        sh("envman add --key BITRISE_TEST_LAB_APK --value $BITRISE_RELEASE_APK")
    end

    private_lane :clean_up do
        sh("rm $VERSION_NAME_PATH")
        sh("rm $RELEASE_NOTES_PATH")
    end
end
